<!doctype html>
<html lang="zh-CN" ng-app="qingniwan.admin">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>INVITE有你更精彩</title>
    <meta name="keywords" content=""/>
    <meta name="description" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="/plugins/bootstrap/css/bootstrap.min.css">
    <!-- main.css-->
    <link rel="stylesheet" type="text/css" href="/css/admin/main.css">
    <!-- iconfont.css-->
    <link rel="stylesheet" type="text/css" href="/fonts/iconfont.css">
    <!-- 引入自定义的 customOfWebUploader-->
   <!-- <link rel="stylesheet" type="text/css" href="/WebUploaderConfig/customOfWebUploader.css">-->
    <style>
        p {
            margin: 0;
        }

        .contentStyle {
            max-width: 790px;
            margin-left: auto;
            margin-right: auto;
            padding-top: 25px;
            padding-left: 20px;
            padding-right: 20px;

        }

        .addSectionImg {
            padding: 10px 50px;
        }

        textarea {
            resize: none;
        }

        .sectionImgForPreview {
            max-width: 100%;
        }

        .ifShowActionOptions {
            display: none
        }

        .webuploader-pick:before,
        .webuploader-pick:after {
            padding-top: 0 !important;
        }

        /*  .PosterForContainer {
              position: relative;
              max-width: 750px;
          }
            .PosterForContainer .addSectionPictureBtn {
              position: absolute;
              width:750px;
              left: 0;
              right: 0;
              top: 0;
              opacity: 0;
          }

          .PosterForContainer .addSectionPictureBtnControls {
              position: absolute !important;
              top: 0 !important;
           }
          .PosterForContainer:hover{
              transition: .3s all ease-in-out;
              -webkit-box-shadow: 0px 2px 26px 2px rgba(94, 138, 236, 0.65);;
              -moz-box-shadow: 0px 2px 26px 2px rgba(94, 138, 236, 0.65);;
              box-shadow: 0px 2px 26px 2px rgba(94, 138, 236, 0.65););
              z-index: 100;

          }
          .PosterForContainer:hover .addSectionPictureBtn {
              margin-right: 10px;
              background: rgb(41, 39, 42);
              opacity: .82;
              color: #fff;
              border: 2px solid #fff;
              border-radius: 0;
          }
       */
        .sectionImgFormContainer {
            position: relative;
            max-width: 375px;
        }

        .sectionImgFormContainer .thumbnail {
            padding: 0;
            margin-bottom: 0;
            border: 0 none;
            border-radius: 0;
        }

        .sectionImgFormContainer .addSectionPictureBtn {
            position: absolute;
            width: 375px;
            left: 0;
            right: 0;
            top: 0;
            opacity: 0;
        }

        .addSectionPictureBtnControls {
            position: absolute !important;
            top: 0 !important;
        }

        .bottomOperationGrunp {
            position: absolute;
            top: 48PX;
            display: none;
        }

        .sectionImgFormContainer:hover {
            transition: .3s all ease-in-out;
            -webkit-box-shadow: 0px 2px 26px 2px rgba(0,0,0,0.3);
            -moz-box-shadow: 0px 2px 26px 2px rgba(0,0,0,0.3);
            box-shadow: 0px 2px 26px 2px rgba(0,0,0,0.3);
        );
            z-index: 100;

        }

        .sectionImgFormContainer:hover .addSectionPictureBtn {
            margin-right: 10px;
            background: rgb(41, 39, 42);
            opacity: .82;
            color: #fff;
            border: 2px solid #fff;
            border-radius: 0;
        }

        .sectionImgFormContainer:hover .bottomOperationGrunp {
            display: block;
        }

        .customBtnStyle {
            margin-right: 10px;
            background: rgb(41, 39, 42);
            opacity: .82;
            color: #fff;
            border-radius: 0;
            border: 2px solid #fff;
        }

        .customBtnStyle:hover,.customBtnStyle:active:focus, .customBtnStyle:focus{
            color: #fff !important;
        }
        .confirmBtn{
            margin-bottom: 150px;
        }

    </style>

</head>
<body ng-controller="specialPublishController" ng-init="initializeBaseData()" class="ng-scope">

<div class="J_container_overflow">

    <!-- top nav -->
    <div class="wui-topnav">
        <div class="row">
            <div class="col-md-1 col-xs-12 logo">
                <img src="/images/admin/logo.svg">
            </div>
            <div class="col-md-11 col-xs-12 J_topnav-padding">
                <ul class="wui-topnav-ul">
                    <li><a href="/?source=1">全部内容</a></li>
                    <li><a href="/Qnw/release">发布内容</a></li>
                    <li><a href="/special/index">专题管理</a></li>
                    <li class="active"><a href="/special/create">发布专题</a></li>
                    <li><a href="/collection/index">专集管理</a></li>
                    <li><a href="/collectioneditor/index">发布专集</a></li>
                   <!-- <li><a href="/usercontrol/index">用户管理</a></li>-->
                    <li><a href="/statistics/index">数据统计</a></li>
                    <li><a href="/feedbacks/index">反馈管理</a></li>
                   <!-- <li><a href="/setting/index">管理员设置</a></li>-->
                </ul>
                <li class="J_account pull-right wui-topnav-login" ng-click="logout()">&nbsp;&nbsp;退出</li>
                <li class="J_account pull-right">您好，<?php session_start();
                    echo $_SESSION['userName']; ?></li>
                <li class="pull-right wui-topnav-publish J_topnav_publish" data-toggle="modal" data-target=".create-event">
                </li>
            </div>
        </div>
    </div>

    <!-- content -->
    <div class="contentStyle">
        <!--上传海报图片-->
        <div class="PosterForContainer">
            <p>
                                    <span id="webuploaderofPoster">
                                        <!-- 用来存放缩略图 -->
                                         <span id="filePickerofPoster">添加海报图片</span>
                                         <span id="fileListofPoster"></span>
                                     </span>
            </p>
        </div>
        <div class="form-group">
            <label class="control-label">专题名称</label>
            <input type="text" class="form-control" ng-model="releaseForSpecial.title">
        </div>
        <div class="form-group">
            <label class="control-label">专题描述</label>
            <textarea rows="5" cols="20" type="text" class="form-control ng-pristine ng-untouched ng-valid" ng-model="releaseForSpecial.specialDescribe"></textarea>
        </div>
        <div class="form-group custom_hidden">
            <label class="control-label">模板链接</label>
            <input type="text" class="form-control" ng-model="releaseForSpecial.templateUrl">
        </div>
        <div class="form-group">
            <label class="control-label">链接地址</label>
            <input type="text" class="form-control" ng-model="releaseForSpecial.url" readonly>
        </div>
        <div class="form-group">
            <label class="control-label">城市</label>
            <select class="form-control wui-inline"
                    ng-options="item.cityName for item in cities track by item.cityID"
                    ng-model="releaseForSpecial.currentSelectedCity"
                    ng-change="updatePulishData()"></select>
        </div>
        <div class="form-group J_sectionImgByRepeatArry">
            <label class="control-label">专题内容区域</label>
        </div>
        <div class="form-group">
            <button type="button" class="btn btn-info addSectionImg" ng-click="addSectionImg()">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </button>
        </div>
        <div class="text-center">
            <!--<input type="button" name="button" id="button" value="取消" onClick="location.href='/?source=1'"/>-->
            <button id="J_Publish" type="button" class="btn btn-primary btn-lg center-block ng-binding confirmBtn" ng-bind="releaseForSpecial.btnText" ng-click="releaseBtnForSpecial()">
                确认发布
            </button>
        </div>
    </div>
</div>

<!-- 后台动态接口 -->
<div class="interface-info">
    <input id="J_default_interface" type="hidden" value="<?php echo $source[$sourceid]['interface']; ?>">
    <input id="J_default_form" type="hidden" value="<?php echo $source[$sourceid]['name']; ?>">
    <input id="J_default_city" type="hidden" value="<?php echo current($cityinfo)['uuid']; ?>">
</div>

<script type="text/javascript">
    // 添加全局站点信息1
    var BASE_URL = '/webuploader';
</script>

<!-- jquery -->
<script type="text/javascript" src="/js/framwork/jquery-1.11.1.min.js"></script>

<!-- bootstrap js -->
<script type="text/javascript" src="/plugins/bootstrap/js/bootstrap.min.js"></script>

<!-- angular js -->
<script type="text/javascript" src="/js/framwork/angular.min.js"></script>

<!--自定义工具类-->
<script type="text/javascript" src="/js/model/controllers/specialPublishController.js"></script>
<script type="text/javascript" src="/js/model/factory/H5Factory.js"></script>
<!--后台返回的数据-->
<script>
    qingniwan.value('baseData', {
        mode: '<?php echo $mode?>' // 这里定义页面要执行的交互模式, create 为创建模式, edit 为编辑模式.
    });
</script>

<!-- artDialog -->
<link rel="stylesheet" href="/plugins/artDialog/css/ui-dialog.css"/>
<script src="/plugins/artDialog/dist/dialog-min.js"></script>

<!-- 百度地图地址解析 -->
<!--<script type="text/javascript" src="https://api.map.baidu.com/api?v=2.0&ak=HkErbUAcRl98Csyp0dRzZGMj&s=1"></script>-->

<!-- bootstrap datetimepicker -->
<link href="/plugins/bootstrapdatetime/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
<script type="text/javascript" src="/plugins/bootstrapdatetime/bootstrap-datetimepicker.min.js"></script>
<!--<script type="text/javascript" src="/plugins/bootstrapdatetime/bootstrap-datetimepicker.zh-CN.js"></script>-->

<!-- webuploader -->
<link rel="stylesheet" href="/plugins/webuploader-0.1.5/webuploader.css">
<script src="/plugins/webuploader-0.1.5/webuploader.js"></script>

<script type="text/javascript">
    var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
    document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F67c4841095cbee8275705e1f6224a3c7' type='text/javascript'%3E%3C/script%3E"));
</script>

<!-- cropper -->
<link rel="stylesheet" href="/plugins/cropper/cropper.css">

<script src="/plugins/cropper/cropper.js"></script>
<!--<script src="/plugins/cropper/uploader.js"></script>-->

<!-- angular-ueditor 富文本编辑器 -->
<script type="text/javascript" src="/plugins/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/plugins/ueditor/ueditor.all.min.js"></script>
<script type="text/javascript" src="/plugins/angular-ueditor/dist/angular-ueditor.js"></script>

<!-- zeroClipboard -->
<script src="/plugins/zeroclipboard/dist/ZeroClipboard.min.js"></script>

</body>
</html>